var https = require('https');
var fs = require('fs');

var search = function(response) {
	var host = process.argv[2] || "http-api.openbloomberg.com";
	var port = 443

	var options = {
		host: host,
		port: port,
		path: '/request?ns=blp&service=refdata&type=HistoricalDataRequest',
		method: 'POST',
		key: fs.readFileSync('hackillinois_spring_2015_038.key'),
		cert: fs.readFileSync('hackillinois_spring_2015_038.crt'),
		ca: fs.readFileSync('bloomberg.crt')
	};

	var req = https.request(options, function(res) {
		//console.log("statusCode: ", res.statusCode);
		//console.log("headers: ", res.headers);

		res.on('data', function(d) {
		  console.log("Data Response Generated by ");
		  response.write(d);
		  response.end();
		});
	});

	req.write(JSON.stringify( {
		"securities": ["IBM US Equity", "AAPL US Equity"],
		"fields": ["PX_LAST", "OPEN"],
		"startDate": "20120101",
		"endDate": "20120105",
		"periodicitySelection": "DAILY"
	}));
	req.end();

	req.on('error', function(e) {
		console.log("Error Response Generated");
		response.write(e);
		response.end();
	});

}
exports.search = search;